### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by fredsamhaak** [mueller-lab/TwinNet#3]
Dear @mueller-lab,

Thanks for your great DL model. I am trying to test it these days but stuck on the first step: installation on my Ubuntu system.
I've found that both the `requirements.txt` and the `twinnetworkenv.yml` are for win-64 platform. Would you pls give me the corresponding files for Ubuntu? Thanks in advance.

Have a nice day!

**Comment by hernanmorales-navarrete** [comment]
Dear @fredsamhaak 

The .txt and .yml files for the installation in linux are now added in the repository: https://github.com/mueller-lab/TwinNet/tree/main/installation

Best
