### ISSUE TITLE
running segmention

### ISSUE THREAD

**Issue by Leondyw** [mueller-lab/TwinNet#5]
Dear authors,
        I try to run the segmention code .
```python 
(twinnetworkenv) C:\TwinNet-main\code\Scripts\segmentation>python main.py -i C:\TwinNet-main\data\segmentation_data\dataset_example\TIFFs\-A004--PO01\images  -m C:\TwinNet-main\data\segmentation_model\saved_model  -o D:\zebrafish_deeplearn\output
[INFO][SEGMENTATION MODEL] Loaded.
```
The results I got are above,but idont have any outputs in the file .how should i do to solve this problem . thank you

**Comment by Nikantou** [comment]
Dear @Leondyw,

Thank you for your question.

Based on the input path that you provided, the image data is stored according to the structure of the example data as follows:
C:/TwinNet-main/data/segmentation_data/dataset_example/TIFFs/-A004--PO01/images

In this case, the input path should be the following:
C:/TwinNet-main/data/segmentation_data/

If you wish to use different input path structures, you can adjust the format for image file search in the scripts in your [segmentation](https://github.com/mueller-lab/TwinNet/tree/main/code/Scripts/segmentation/tools_embryo_segmentation) copy.

Based on this, we tested the scripts and get the following result:

```
[INFO][DATASET PATH] C:/TwinNet-main/data/segmentation_data/dataset_example/TIFFs
[INFO][DATASET NAME] dataset_example
[INFO][NUM FILES] -A004--PO01: 50
[INFO][FILETYPE] .tif
[INFO][SEGMENTATION MODEL] Loaded.

C:/TwinNet-main/data/segmentation_data/dataset_example/TIFFs/-A004--PO01//images/
===========================================================
=    START: Sequence segmentation and storage as JSON.    =
===========================================================
===========================================
=    DONE: Saved predictions as JSONs.    =
=    Duration: 0:00:28.966085             =
===========================================
```

We added this additional information to the given information in [Scripts](https://github.com/mueller-lab/TwinNet/tree/main/code/Scripts).

Best regards
