### ISSUE TITLE
ModelTN_v2

### ISSUE THREAD

**Issue by Leondyw** [mueller-lab/TwinNet#6]
Dear authors:
        I have in trouble of finding 'ModelTN_v2'.  This model is mentioned in the script of 'Deviation_development_inhibitor_detection
'. It's in the cell 7 ,the "model name' .
        I would appreciate greatly if you could help me work out it.Thanks

**Comment by Nikantou** [comment]
Dear @Leondyw,

Thank you for your question. In the script "Deviation_development_inhibitor_detection" the model name "ModelTN_v2" references this Twin Network model for zebrafish embryos: ["model_trained_more_data"](https://github.com/mueller-lab/TwinNet/tree/main/data/twinnet_models/tn_models_zebrafish/model_trained_more_data).

The corresponding model file can be downloaded from the [repository](https://github.com/mueller-lab/TwinNet/tree/main/data/twinnet_models/tn_models_zebrafish/model_trained_more_data) or the referenced page in the [Twin Network data README.md](https://github.com/mueller-lab/TwinNet/blob/main/data/README.md). When using the model downloaded from this repository or the referenced page saved with a different format than the H5 format, please modify the model path in code block 8 accordingly. 

We have added a comment in the "Deviation_development_inhibitor_detection" script to clarify the model version.

Best regards
